---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: fortune-cookie-api
spec:
  replicas: 1
  template:
    metadata:
      name: fortune-cookie-api
      labels:
        app: fortune-cookie-api
    spec:
      containers: 
        - name: app
          image: docker.io/simulalex/fortune-cookie-api:1
          ports:
            - name: http
              containerPort: 8080
      imagePullSecrets:
        - name: bluemix-default-secret
