---
kind: Service
apiVersion: v1
metadata:
  name: fortune-cookie-api
spec:
  selector:
    app: fortune-cookie-api
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
